### ISSUE TITLE
The plugin is not working on vim 7.4

### ISSUE THREAD

**Issue by MohamedBassem** [sourcegraph/sourcegraph-vim#14]
Hi all,

I tried installing the plugin using Vundler on vim 7.4 but the command `:GRAPH` didn't get registered.

Here's a terminal recording of the bug:
[![asciicast](https://asciinema.org/a/49219.png)](https://asciinema.org/a/49219)

If you have any other question, please let me know.

Thank you!

**Comment by uforic** [comment]
Hey Mohamed, thanks for reporting this.Looking into this now. I just merged in a diagnostic file, and added a section to the README about running it.

Mind running this, and double checking that the output is successful or if there an issue reported? Will continue to dig into whether this is a Vundle specific issue.

**Comment by MohamedBassem** [comment]
Hi, I ran the diagnosis file, reported something about missing `godefinfo` so I installed it and ran `VundleUpdate` and the same problem still happens. Here's the diagnosis file's output:
```
-------------------------
Running diagnostic for Sourcegraph for your editor. If you need to override values, pass them in as arugments as such:
python diagnostic.py -g /path/to/gopath -b /path/to/go/binary
-------------------------
----Printing settings object with default values.
{"SG_CHANNEL": "mohamedbassem-95ab4fd46f1976471843fcf8071ef95b9f63", "GOPATH": "/home/mohamedbassem/repos/go", "SG_BASE_URL": "https://sourcegraph.com", "GOBIN": "/usr/local/go/bin/go", "EditorType": "undefined", "SG_SEND_URL": "https://grpc.sourcegraph.com", "VersionMinor": 1, "PATH": "/home/mohamedbassem/bin:/home/mohamedbassem/.rbenv/shims:/home/mohamedbassem/.rbenv/bin:/home/mohamedbassem/.rbenv/versions/2.3.0/bin:/home/mohamedbassem/.rbenv/libexec:/home/mohamedbassem/.rbenv/plugins/ruby-build/bin:/home/mohamedbassem/.rbenv/shims:/home/mohamedbassem/.rbenv/bin:/home/mohamedbassem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/mohamedbassem/bin:/home/mohamedbassem/usr/bin:/usr/local/go/bin:/home/mohamedbassem/repos/go/bin:/home/mohamedbassem/.fzf/bin:/snap/bin:/home/mohamedbassem/bin:/home/mohamedbassem/usr/bin:/usr/local/go/bin:/home/mohamedbassem/repos/go/bin", "ENABLE_LOOKBACK": true}
----VERIFY GOPATH and PATH settings, to ensure that the go binary is in the PATH, and GOPATH is correctly set.
----Validating settings object. If value is not none, Sourcegraph for your editor is not configured properly.
--------Checking if shell is supported.
--------Checking if `pwd` works on the shell.
--------Checking GOPATH settings.
--------Running go binary and checking version.
--------Checking if godefinfo binary is in $GOPATH/bin, and running godefinfo -v.
----VERIFY output of validate settings is None: None
----Assembling Sourcegraph object.
----VERIFY that $GOPATH/bin is in the path. PATH = /home/mohamedbassem/bin:/home/mohamedbassem/.rbenv/shims:/home/mohamedbassem/.rbenv/bin:/home/mohamedbassem/.rbenv/versions/2.3.0/bin:/home/mohamedbassem/.rbenv/libexec:/home/mohamedbassem/.rbenv/plugins/ruby-build/bin:/home/mohamedbassem/.rbenv/shims:/home/mohamedbassem/.rbenv/bin:/home/mohamedbassem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/mohamedbassem/bin:/home/mohamedbassem/usr/bin:/usr/local/go/bin:/home/mohamedbassem/repos/go/bin:/home/mohamedbassem/.fzf/bin:/snap/bin:/home/mohamedbassem/bin:/home/mohamedbassem/usr/bin:/usr/local/go/bin:/home/mohamedbassem/repos/go/bin
----Testing browser settings.
----VERIFY browser opens.




-------------------------
Diagnostic completed.
-------------------------

```

**Comment by uforic** [comment]
Awesome, thats good - checking on a Vundle ENV as we speak, stay tuned. Just double checking - with that last command, a browser window should open pointed at https://sourcegraph.com/-/channel/mohamedbassem-95ab4fd46f1976471843fcf8071ef95b9f63 - did you see that window open?

**Comment by MohamedBassem** [comment]
Yes It opened correctly :+1:

**Comment by uforic** [comment]
yo! oh man, I wish I'd checked earlier. You'll need Python installed in your Vim. I see it isn't there from the vim --version command.

I got the silent failure behavior when Python wasn't compiled into my vim (default on Ubuntu Linux). 

I followed the directions here to get that set up:
http://stackoverflow.com/questions/10864042/how-to-check-python-version-that-vim-was-compiled-with

Let me know if that does it!

**Comment by MohamedBassem** [comment]
Well python is installed. `:echo has('python3')` prints 1. In the demo, I piped it through `head` to avoid filling the screen. That's the full version : 
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     

```

**Comment by MohamedBassem** [comment]
The thing is. `:GRAPH` doesn't seem to be registered at all. Not an error when running it or something.
